In [1]:
#===============================
#Project (Recommended System)

In [32]:
import pandas as pd
import numpy as np

In [33]:
movies=pd.read_csv('movie1.csv')
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",04-09-1992,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],26-12-2011,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",13-10-2013,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",03-05-2012,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",05-08-2005,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [34]:
credits=pd.read_csv("movie2.csv")
credits

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\1928751767.py:1: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264) have mixed types. Specify dtype option on import or set low_memory=False.
  credits=pd.read_csv("movie2.csv")

,movie_id,title,cast,crew,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4808,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4809,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4810,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4811,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4812,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [36]:
credits.head()

,movie_id,title,cast,crew,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
credits.head(1)['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'],
      dtype=object)

In [37]:
credits=credits[['movie_id','title','cast','crew']]
credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4808,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4809,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4810,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4811,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4812,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [38]:
#merging
movies=movies.merge(credits,on='title')
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [39]:
movies.shape

(4809, 23)

In [11]:
#information
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   object
 21  cast                  4809 non-null   object
 22  crew                  4805 non-null   object
dtypes: float64(3), int64(4), object(16)
memory usage: 864.2+ KB

In [40]:
#choose only those columns which are in use for recommendation
movies=movies[['genres','keywords','movie_id','title','overview','cast','crew']]
movies

,genres,keywords,movie_id,title,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",49529,John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,[],[],126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [41]:
#missing data
movies.isnull().sum()

genres      0
keywords    0
movie_id    0
title       0
overview    3
cast        0
crew        4
dtype: int64

In [42]:
#drop rows
movies.dropna(inplace=True)

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\3787226279.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [43]:
#info
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4802 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4802 non-null   object
 1   keywords  4802 non-null   object
 2   movie_id  4802 non-null   object
 3   title     4802 non-null   object
 4   overview  4802 non-null   object
 5   cast      4802 non-null   object
 6   crew      4802 non-null   object
dtypes: object(7)
memory usage: 300.1+ KB

In [44]:
#null
movies.isnull().sum()

genres      0
keywords    0
movie_id    0
title       0
overview    0
cast        0
crew        0
dtype: int64

In [45]:
#duplicate
movies.duplicated().sum()

0

In [46]:
#reading data
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [47]:
#preprocessing

In [48]:
#convert (string of list) into list
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [49]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [50]:
movies['genres']=movies['genres'].apply(convert)

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\1567952790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(convert)

In [23]:
movies.head()

,genres,keywords,movie_id,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",49529,John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [51]:
movies['keywords']=movies['keywords'].apply(convert)

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\1621871954.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(convert)

In [52]:
movies.head()

,genres,keywords,movie_id,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",49529,John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [53]:
#cast
def convert(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [54]:
movies['cast']=movies['cast'].apply(convert)

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\3504945513.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(convert)

In [55]:
movies.head()

,genres,keywords,movie_id,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",49529,John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [57]:
#dropping
movies.drop('crew',axis=1,inplace=True)

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\825578325.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.drop('crew',axis=1,inplace=True)

In [58]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4802 entries, 0 to 4808
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4802 non-null   object
 1   keywords  4802 non-null   object
 2   movie_id  4802 non-null   object
 3   title     4802 non-null   object
 4   overview  4802 non-null   object
 5   cast      4802 non-null   object
dtypes: object(6)
memory usage: 262.6+ KB

In [59]:
movies.head()

,genres,keywords,movie_id,title,overview,cast
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]"
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]"
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]"
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]"
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",49529,John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]"

In [60]:
#since (column='overview')is a string and we will have to convert it in list
movies['overview']=movies['overview'].apply(lambda x:x.split())

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\1798380959.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview']=movies['overview'].apply(lambda x:x.split())

In [61]:
movies.head()

,genres,keywords,movie_id,title,overview,cast
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]"
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]"
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]"
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]"
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]"

In [62]:
#replace gaps between two words
movies['genre']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\2474306204.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genre']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\2474306204.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\2474306204.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])

In [63]:
movies.head()

,genres,keywords,movie_id,title,overview,cast,genre
0,"[Action, Adventure, Fantasy, Science Fiction]","[cultureclash, future, spacewar, spacecolony, ...",19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[Action, Adventure, Fantasy, ScienceFiction]"
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[Adventure, Fantasy, Action]"
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]","[Action, Adventure, Crime]"
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]","[Action, Crime, Drama, Thriller]"
4,"[Action, Adventure, Science Fiction]","[basedonnovel, mars, medallion, spacetravel, p...",49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[Action, Adventure, ScienceFiction]"

In [64]:
#generate new column
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\4133001349.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']

In [65]:
movies.head()

,genres,keywords,movie_id,title,overview,cast,genre,tags
0,"[Action, Adventure, Fantasy, Science Fiction]","[cultureclash, future, spacewar, spacecolony, ...",19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, Science Fiction]","[basedonnovel, mars, medallion, spacetravel, p...",49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili..."

In [66]:
#new column
new_df=movies[['movie_id','title','tags']]
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [67]:
#convert in string
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\201885817.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [68]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [69]:
#Convert in lower
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\2718411475.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [70]:
import nltk

In [71]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [72]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return" ".join(y)

In [73]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\rajkr\AppData\Local\Temp\ipykernel_9920\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [76]:
#Vectorisation
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [77]:
vectors=cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [78]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [79]:
#here instead of euclidean we will calculate the cosine distance between the vectors to find
#the similarity between the movies
#the more the angle less will be the similarity between the movies
#the less the angle between the two vectors more the similarities
#the higher the dimension means if we are having 5000 or 10000 or more values in the dataset here euclidean distance will fail
#so for that instead of euclidean distance we will use Cosine distance

In [80]:
from sklearn.metrics.pairwise import cosine_similarity

In [81]:
cosine_similarity(vectors)#indicating the similarity of one movie with the rest of all the movies

array([[1.        , 0.0836242 , 0.0862796 , ..., 0.04399059, 0.        ,
        0.        ],
       [0.0836242 , 1.        , 0.06253054, ..., 0.0239114 , 0.        ,
        0.02654659],
       [0.0862796 , 0.06253054, 1.        , ..., 0.02467069, 0.        ,
        0.        ],
       ...,
       [0.04399059, 0.0239114 , 0.02467069, ..., 1.        , 0.03924588,
        0.04189458],
       [0.        , 0.        , 0.        , ..., 0.03924588, 1.        ,
        0.08714204],
       [0.        , 0.02654659, 0.        , ..., 0.04189458, 0.08714204,
        1.        ]])

In [82]:
cosine_similarity(vectors).shape

(4802, 4802)

In [83]:
similarity=cosine_similarity(vectors)
similarity

array([[1.        , 0.0836242 , 0.0862796 , ..., 0.04399059, 0.        ,
        0.        ],
       [0.0836242 , 1.        , 0.06253054, ..., 0.0239114 , 0.        ,
        0.02654659],
       [0.0862796 , 0.06253054, 1.        , ..., 0.02467069, 0.        ,
        0.        ],
       ...,
       [0.04399059, 0.0239114 , 0.02467069, ..., 1.        , 0.03924588,
        0.04189458],
       [0.        , 0.        , 0.        , ..., 0.03924588, 1.        ,
        0.08714204],
       [0.        , 0.02654659, 0.        , ..., 0.04189458, 0.08714204,
        1.        ]])

In [84]:
similarity[0]

array([1.        , 0.0836242 , 0.0862796 , ..., 0.04399059, 0.        ,
       0.        ])

In [85]:
similarity[1]

array([0.0836242 , 1.        , 0.06253054, ..., 0.0239114 , 0.        ,
       0.02654659])

In [86]:
#enumerate
#we use enumerate so that while sorting the vectors we dont loss the realtion with one vectors with another
list(enumerate(similarity[0]))

[(0, 1.0000000000000002),
 (1, 0.08362420100070908),
 (2, 0.08627959628145762),
 (3, 0.07299318686018119),
 (4, 0.2080125735844609),
 (5, 0.10795837927188262),
 (6, 0.039722906114947866),
 (7, 0.167093470609201),
 (8, 0.05751973085430508),
 (9, 0.09656090991705352),
 (10, 0.12659242088545833),
 (11, 0.09443843292997713),
 (12, 0.09078412990032037),
 (13, 0.044844852933087494),
 (14, 0.15191090506255),
 (15, 0.06201736729460422),
 (16, 0.10256410256410256),
 (17, 0.13797289239745258),
 (18, 0.11168711865749101),
 (19, 0.0826898230594723),
 (20, 0.057289189923154626),
 (21, 0.10984700727621793),
 (22, 0.06677805632941779),
 (23, 0.08770580193070292),
 (24, 0.053376051268362375),
 (25, 0.033757978902788886),
 (26, 0.17505471314812437),
 (27, 0.1971041319963609),
 (28, 0.14153462926807445),
 (29, 0.06362847629757777),
 (30, 0.06661733875264912),
 (31, 0.1849000654084097),
 (32, 0.08483796839677037),
 (33, 0.12810252304406972),
 (34, 0.0),
 (35, 0.12810252304406972),
 (36, 0.19312181983410703),
 (37, 0.07897471897389846),
 (38, 0.08006407690254357),
 (39, 0.10675210253672475),
 (40, 0.075955452531275),
 (41, 0.18685673434682065),
 (42, 0.0),
 (43, 0.1319717610643751),
 (44, 0.03413943709994594),
 (45, 0.10087125544480038),
 (46, 0.16477051091432687),
 (47, 0.21204880838762138),
 (48, 0.084103426706236),
 (49, 0.05751973085430508),
 (50, 0.11322770341445956),
 (51, 0.09781383788084239),
 (52, 0.16898159235484367),
 (53, 0.042796049251091296),
 (54, 0.030816677568068284),
 (55, 0.06947334742918748),
 (56, 0.16694514082354447),
 (57, 0.02387049580131443),
 (58, 0.06726727939963124),
 (59, 0.08896008544727063),
 (60, 0.018248296715045298),
 (61, 0.2562050460881395),
 (62, 0.0826898230594723),
 (63, 0.0806970043558403),
 (64, 0.05847053462046861),
 (65, 0.019418390934515434),
 (66, 0.022205779584216375),
 (67, 0.18427434427242975),
 (68, 0.14867525836251314),
 (69, 0.02614881801842454),
 (70, 0.10003126465607107),
 (71, 0.07325794357582566),
 (72, 0.16012815380508713),
 (73, 0.033389028164708894),
 (74, 0.22205779584216379),
 (75, 0.10256410256410256),
 (76, 0.09342836717341034),
 (77, 0.013937366833451514),
 (78, 0.05063696835418333),
 (79, 0.08200923681047297),
 (80, 0.049813548138671795),
 (81, 0.10878565864408421),
 (82, 0.09883324222148016),
 (83, 0.19611613513818402),
 (84, 0.12201777521731262),
 (85, 0.12810252304406974),
 (86, 0.06933752452815364),
 (87, 0.13533299049019168),
 (88, 0.08920515501750789),
 (89, 0.05661385170722978),
 (90, 0.06052275326688024),
 (91, 0.19223226273338134),
 (92, 0.06150692760785473),
 (93, 0.09245003270420486),
 (94, 0.21182963643408081),
 (95, 0.1617875572323585),
 (96, 0.10127393670836667),
 (97, 0.09058216273156766),
 (98, 0.07502344849205331),
 (99, 0.026688025634181187),
 (100, 0.06827887419989188),
 (101, 0.10003126465607107),
 (102, 0.14235407108686474),
 (103, 0.09930726528736966),
 (104, 0.055749467333806056),
 (105, 0.10241831129983783),
 (106, 0.06100888760865632),
 (107, 0.06004805767690767),
 (108, 0.18490006540840973),
 (109, 0.06405126152203486),
 (110, 0.04441155916843275),
 (111, 0.1709352016769265),
 (112, 0.07692307692307693),
 (113, 0.042796049251091296),
 (114, 0.04529108136578383),
 (115, 0.04358136336404089),
 (116, 0.07007127538005775),
 (117, 0.05947010334500526),
 (118, 0.03320903209244786),
 (119, 0.04318335170875305),
 (120, 0.0),
 (121, 0.11149893466761211),
 (122, 0.14153462926807445),
 (123, 0.13074409009212268),
 (124, 0.06661733875264912),
 (125, 0.08752735657406217),
 (126, 0.12503908082008883),
 (127, 0.1621424235993525),
 (128, 0.0),
 (129, 0.08483796839677037),
 (130, 0.026688025634181187),
 (131, 0.10390486669322622),
 (132, 0.06598588053218755),
 (133, 0.02830692585361489),
 (134, 0.12810252304406972),
 (135, 0.0),
 (136, 0.022875450543583874),
 (137, 0.02973505167250263),
 (138, 0.1282051282051282),
 (139, 0.11916871834484359),
 (140, 0.044844852933087494),
 (141, 0.08627959628145762),
 (142, 0.08362420100070908),
 (143, 0.08559209850218259),
 (144, 0.04941662111074008),
 (145, 0.019138975058773818),
 (146, 0.016012815380508715),
 (147, 0.05492350363810897),
 (148, 0.09421114395319916),
 (149, 0.17225077552896437),
 (150, 0.18490006540840964),
 (151, 0.20483662259967564),
 (152, 0.08238525545716345),
 (153, 0.07767356373806174),
 (154, 0.06052275326688024),
 (155, 0.020174251088960076),
 (156, 0.0595843591724218),
 (157, 0.10241831129983782),
 (158, 0.15253477177414312),
 (159, 0.06405126152203486),
 (160, 0.11561170597113389),
 (161, 0.03140371465106639),
 (162, 0.033389028164708894),
 (163, 0.07502344849205331),
 (164, 0.07897471897389846),
 (165, 0.06793662204867575),
 (166, 0.1465158871516513),
 (167, 0.08920515501750789),
 (168, 0.1953545162022017),
 (169, 0.10795837927188262),
 (170, 0.105129283382795),
 (171, 0.022422426466543747),
 (172, 0.20483662259967567),
 (173, 0.023112508176051216),
 (174, 0.10127393670836667),
 (175, 0.07082882469748285),
 (176, 0.02875986542715254),
 (177, 0.0),
 (178, 0.024419314525275217),
 (179, 0.07161148740394328),
 (180, 0.021790681682020446),
 (181, 0.04441155916843275),
 (182, 0.13725270326150324),
 (183, 0.08633531446374632),
 (184, 0.1953545162022017),
 (185, 0.07502344849205331),
 (186, 0.05868830272850543),
 (187, 0.15191090506255),
 (188, 0.021995293510729184),
 (189, 0.11322770341445959),
 (190, 0.08338763984501665),
 (191, 0.04828045495852676),
 (192, 0.04671418358670517),
 (193, 0.09331812717375042),
 (194, 0.0),
 (195, 0.05947010334500526),
 (196, 0.07502344849205331),
 (197, 0.036496593430090596),
 (198, 0.05661385170722978),
 (199, 0.0863667034175061),
 (200, 0.13977131156292244),
 (201, 0.0),
 (202, 0.030816677568068284),
 (203, 0.10984700727621793),
 (204, 0.04883862905055043),
 (205, 0.07548513560963972),
 (206, 0.12691660175143157),
 (207, 0.10003126465607107),
 (208, 0.12326671027227314),
 (209, 0.06677805632941779),
 (210, 0.07502344849205331),
 (211, 0.024419314525275217),
 (212, 0.08716272672808179),
 (213, 0.05868830272850543),
 (214, 0.0),
 (215, 0.06537204504606134),
 (216, 0.06537204504606135),
 (217, 0.084103426706236),
 (218, 0.09078412990032037),
 (219, 0.2046468711716401),
 (220, 0.04671418358670517),
 (221, 0.09781383788084239),
 (222, 0.12659242088545833),
 (223, 0.07944581222989573),
 (224, 0.06862635163075162),
 (225, 0.03026137663344012),
 (226, 0.08238525545716345),
 (227, 0.12955005512625914),
 (228, 0.12303443814151493),
 (229, 0.108094949066235),
 (230, 0.0),
 (231, 0.1373087590952724),
 (232, 0.13355611265883557),
 (233, 0.08483796839677037),
 (234, 0.07502344849205331),
 (235, 0.11503946170861017),
 (236, 0.06537204504606135),
 (237, 0.1261107739106075),
 (238, 0.10741723110591492),
 (239, 0.04671418358670517),
 (240, 0.07692307692307693),
 (241, 0.10390486669322622),
 (242, 0.09245003270420486),
 (243, 0.09078412990032037),
 (244, 0.08006407690254357),
 (245, 0.07548513560963972),
 (246, 0.0),
 (247, 0.04441155916843275),
 (248, 0.16694514082354447),
 (249, 0.0),
 (250, 0.04134491152973615),
 (251, 0.02001601922563589),
 (252, 0.06201736729460422),
 (253, 0.06862635163075162),
 (254, 0.0),
 (255, 0.14322297480788657),
 (256, 0.07897471897389846),
 (257, 0.017471413945365305),
 (258, 0.06052275326688024),
 (259, 0.20464687117164013),
 (260, 0.02387049580131443),
 (261, 0.10604746049596296),
 (262, 0.09805806756909202),
 (263, 0.0),
 (264, 0.027066598098038335),
 (265, 0.1207011373963169),
 (266, 0.06537204504606135),
 (267, 0.05195243334661311),
 (268, 0.029235267310234306),
 (269, 0.1283881477532739),
 (270, 0.09342836717341034),
 (271, 0.027461751819054483),
 (272, 0.020846909961254163),
 (273, 0.08861469461982083),
 (274, 0.16984155512168933),
 (275, 0.06280742930213278),
 (276, 0.05272904491779212),
 (277, 0.1386750490563073),
 (278, 0.09058216273156766),
 (279, 0.0),
 (280, 0.06477502756312958),
 (281, 0.022205779584216375),
 (282, 0.027461751819054483),
 (283, 0.01813094310734737),
 (284, 0.019277164398874672),
 (285, 0.07710865759549869),
 (286, 0.025976216673306556),
 (287, 0.027066598098038335),
 (288, 0.04529108136578383),
 (289, 0.06280742930213278),
 (290, 0.04883862905055043),
 (291, 0.08770580193070292),
 (292, 0.029235267310234306),
 (293, 0.14153462926807445),
 (294, 0.10390486669322622),
 (295, 0.038277950117547636),
 (296, 0.04399058702145837),
 (297, 0.0),
 (298, 0.05868830272850543),
 (299, 0.19096396641051544),
 (300, 0.11020775375559676),
 (301, 0.06933752452815364),
 (302, 0.027461751819054483),
 (303, 0.0651552217454565),
 (304, 0.20672455764868075),
 (305, 0.10529962529853128),
 (306, 0.10736246830291345),
 (307, 0.06677805632941779),
 (308, 0.06163335513613657),
 (309, 0.03039738350583688),
 (310, 0.17093520167692652),
 (311, 0.10003126465607107),
 (312, 0.05413319619607667),
 (313, 0.0),
 (314, 0.08238525545716345),
 (315, 0.0),
 (316, 0.0),
 (317, 0.0),
 (318, 0.1307440900921227),
 (319, 0.030816677568068284),
 (320, 0.0),
 (321, 0.23076923076923073),
 (322, 0.029235267310234306),
 (323, 0.02387049580131443),
 (324, 0.09607689228305229),
 (325, 0.05661385170722978),
 (326, 0.026688025634181187),
 (327, 0.027066598098038335),
 (328, 0.07897471897389846),
 (329, 0.10003126465607107),
 (330, 0.08798117404291673),
 (331, 0.10675210253672475),
 (332, 0.04774099160262886),
 (333, 0.1180480411624714),
 (334, 0.06793662204867575),
 (335, 0.06827887419989188),
 (336, 0.04441155916843275),
 (337, 0.0),
 (338, 0.04828045495852676),
 (339, 0.04941662111074008),
 (340, 0.08238525545716345),
 (341, 0.17792017089454126),
 (342, 0.019003715589632167),
 (343, 0.02973505167250263),
 (344, 0.022645540682891915),
 (345, 0.0),
 (346, 0.023357091793352585),
 (347, 0.06052275326688024),
 (348, 0.07792865001991967),
 (349, 0.04828045495852676),
 (350, 0.0),
 (351, 0.027066598098038335),
 (352, 0.04169381992250833),
 (353, 0.021591675854376526),
 (354, 0.03626188621469474),
 (355, 0.09078412990032037),
 (356, 0.0),
 (357, 0.08770580193070292),
 (358, 0.030816677568068284),
 (359, 0.020846909961254163),
 (360, 0.07502344849205331),
 (361, 0.12561485860426555),
 (362, 0.11737660545701087),
 (363, 0.023112508176051216),
 (364, 0.1416576493949657),
 (365, 0.08238525545716345),
 (366, 0.0),
 (367, 0.12810252304406972),
 (368, 0.12503908082008885),
 (369, 0.050015632328035534),
 (370, 0.1180480411624714),
 (371, 0.04721921646498856),
 (372, 0.20483662259967564),
 (373, 0.037483165639491674),
 (374, 0.0806970043558403),
 (375, 0.06862635163075162),
 (376, 0.0),
 (377, 0.0),
 (378, 0.05008354224706334),
 (379, 0.05195243334661311),
 (380, 0.0826898230594723),
 (381, 0.0),
 (382, 0.042796049251091296),
 (383, 0.02830692585361489),
 (384, 0.0),
 (385, 0.021790681682020446),
 (386, 0.023357091793352585),
 (387, 0.0),
 (388, 0.08920515501750789),
 (389, 0.025976216673306556),
 (390, 0.0558435593287455),
 (391, 0.02973505167250263),
 (392, 0.0),
 (393, 0.02470831055537004),
 (394, 0.05128205128205128),
 (395, 0.04358136336404089),
 (396, 0.05128205128205128),
 (397, 0.0),
 (398, 0.023357091793352585),
 (399, 0.11694106924093722),
 (400, 0.03140371465106639),
 (401, 0.07792865001991967),
 (402, 0.10336227882434038),
 (403, 0.06052275326688024),
 (404, 0.05492350363810897),
 (405, 0.02050230920261824),
 (406, 0.021025856676559),
 (407, 0.03202563076101743),
 (408, 0.0),
 (409, 0.1180480411624714),
 (410, 0.05195243334661311),
 (411, 0.11678545896676293),
 (412, 0.16724840200141816),
 (413, 0.029235267310234306),
 (414, 0.06988565578146122),
 (415, 0.05063696835418333),
 (416, 0.03580574370197164),
 (417, 0.03494282789073061),
 (418, 0.09058216273156766),
 (419, 0.1319717610643751),
 (420, 0.023112508176051216),
 (421, 0.14153462926807445),
 (422, 0.04100461840523648),
 (423, 0.037229039552497),
 (424, 0.06362847629757777),
 (425, 0.07030539322372283),
 (426, 0.025976216673306556),
 (427, 0.055470019622522904),
 (428, 0.0),
 (429, 0.050015632328035534),
 (430, 0.02387049580131443),
 (431, 0.11102889792108186),
 (432, 0.030816677568068284),
 (433, 0.0),
 (434, 0.03494282789073061),
 (435, 0.0),
 (436, 0.02564102564102564),
 (437, 0.1207011373963169),
 (438, 0.025976216673306556),
 (439, 0.024419314525275217),
 (440, 0.08362420100070908),
 (441, 0.06726727939963124),
 (442, 0.06362847629757777),
 (443, 0.0),
 (444, 0.09883324222148016),
 (445, 0.022875450543583874),
 (446, 0.06362847629757777),
 (447, 0.021025856676559),
 (448, 0.13344012817090595),
 (449, 0.04169381992250833),
 (450, 0.02470831055537004),
 (451, 0.03026137663344012),
 (452, 0.02414022747926338),
 (453, 0.1358732440973515),
 (454, 0.060522753266880225),
 (455, 0.042796049251091296),
 (456, 0.08770580193070292),
 (457, 0.042796049251091296),
 (458, 0.03413943709994594),
 (459, 0.02414022747926338),
 (460, 0.16239958858823),
 (461, 0.031866693647145374),
 (462, 0.03202563076101743),
 (463, 0.0),
 (464, 0.0),
 (465, 0.1706971854997297),
 (466, 0.10423454980627081),
 (467, 0.027461751819054483),
 (468, 0.05913123959890826),
 (469, 0.044844852933087494),
 (470, 0.063077570029677),
 (471, 0.10675210253672475),
 (472, 0.1539670545751043),
 (473, 0.0),
 (474, 0.04318335170875305),
 (475, 0.16012815380508716),
 (476, 0.0),
 (477, 0.05370861555295746),
 (478, 0.08684168428648435),
 (479, 0.11935247900657214),
 (480, 0.0),
 (481, 0.021591675854376526),
 (482, 0.15408338784034142),
 (483, 0.03026137663344012),
 (484, 0.05264981264926564),
 (485, 0.07888947910127371),
 (486, 0.17841031003501578),
 (487, 0.06571520774535256),
 (488, 0.0),
 (489, 0.1706971854997297),
 (490, 0.09930726528736966),
 (491, 0.07502344849205331),
 (492, 0.03039738350583688),
 (493, 0.0),
 (494, 0.21571674297647797),
 (495, 0.0),
 (496, 0.0),
 (497, 0.06677805632941779),
 (498, 0.0),
 (499, 0.025976216673306556),
 (500, 0.0806970043558403),
 (501, 0.15253477177414312),
 (502, 0.07412493166611012),
 (503, 0.0),
 (504, 0.1634301126151534),
 (505, 0.03413943709994594),
 (506, 0.2710098294963041),
 (507, 0.12503908082008883),
 (508, 0.021995293510729184),
 (509, 0.1207011373963169),
 (510, 0.12104550653376048),
 (511, 0.027066598098038335),
 (512, 0.14824986333222023),
 (513, 0.04828045495852676),
 (514, 0.02470831055537004),
 (515, 0.02830692585361489),
 (516, 0.0),
 (517, 0.04318335170875305),
 (518, 0.0),
 (519, 0.0),
 (520, 0.02470831055537004),
 (521, 0.02387049580131443),
 (522, 0.04828045495852676),
 (523, 0.0),
 (524, 0.04671418358670517),
 (525, 0.027874733666903028),
 (526, 0.033389028164708894),
 (527, 0.022205779584216375),
 (528, 0.167093470609201),
 (529, 0.05492350363810897),
 (530, 0.04622501635210243),
 (531, 0.02120949209919259),
 (532, 0.05947010334500526),
 (533, 0.08559209850218259),
 (534, 0.09656090991705352),
 (535, 0.11102889792108189),
 (536, 0.06677805632941779),
 (537, 0.0),
 (538, 0.2706659809803833),
 (539, 0.07412493166611012),
 (540, 0.125081459767525),
 (541, 0.05439282932204211),
 (542, 0.07007127538005775),
 (543, 0.05492350363810897),
 (544, 0.04828045495852676),
 (545, 0.06280742930213278),
 (546, 0.08362420100070908),
 (547, 0.0),
 (548, 0.1416576493949657),
 (549, 0.024419314525275217),
 (550, 0.037229039552497),
 (551, 0.0),
 (552, 0.02875986542715254),
 (553, 0.0),
 (554, 0.04441155916843275),
 (555, 0.027461751819054483),
 (556, 0.12209657262637608),
 (557, 0.0),
 (558, 0.02973505167250263),
 (559, 0.03580574370197164),
 (560, 0.03202563076101743),
 (561, 0.030816677568068284),
 (562, 0.025318484177091666),
 (563, 0.11694106924093722),
 (564, 0.042796049251091296),
 (565, 0.02360960823249428),
 (566, 0.025007816164017767),
 (567, 0.14153462926807447),
 (568, 0.04622501635210243),
 (569, 0.06827887419989188),
 (570, 0.042051713353118),
 (571, 0.10699012312772824),
 (572, 0.020672455764868074),
 (573, 0.023357091793352585),
 (574, 0.06661733875264912),
 (575, 0.05195243334661311),
 (576, 0.2229978693352242),
 (577, 0.03698001308168194),
 (578, 0.1437993271357627),
 (579, 0.02414022747926338),
 (580, 0.1815682598006407),
 (581, 0.26148818018424536),
 (582, 0.037483165639491674),
 (583, 0.08006407690254357),
 (584, 0.024419314525275217),
 (585, 0.04575090108716775),
 (586, 0.09342836717341034),
 (587, 0.02564102564102564),
 (588, 0.11483385035264292),
 (589, 0.03026137663344012),
 (590, 0.06201736729460422),
 (591, 0.021025856676559),
 (592, 0.0),
 (593, 0.04941662111074008),
 (594, 0.18116432546313532),
 (595, 0.0915018021743355),
 (596, 0.05847053462046861),
 (597, 0.027066598098038335),
 (598, 0.06793662204867575),
 (599, 0.04954787398762882),
 (600, 0.08968970586617499),
 (601, 0.053376051268362375),
 (602, 0.06677805632941779),
 (603, 0.025007816164017767),
 (604, 0.0),
 (605, 0.07548513560963972),
 (606, 0.0),
 (607, 0.023112508176051216),
 (608, 0.05751973085430508),
 (609, 0.022875450543583874),
 (610, 0.06201736729460422),
 (611, 0.03580574370197164),
 (612, 0.04774099160262886),
 (613, 0.06052275326688024),
 (614, 0.03413943709994594),
 (615, 0.04941662111074008),
 (616, 0.10795837927188262),
 (617, 0.0),
 (618, 0.0),
 (619, 0.06405126152203486),
 (620, 0.021025856676559),
 (621, 0.0),
 (622, 0.10016708449412667),
 (623, 0.030816677568068284),
 (624, 0.10529962529853128),
 (625, 0.10741723110591492),
 (626, 0.0),
 (627, 0.04774099160262886),
 (628, 0.02414022747926338),
 (629, 0.04941662111074008),
 (630, 0.10003126465607107),
 (631, 0.022205779584216375),
 (632, 0.09656090991705352),
 (633, 0.06598588053218755),
 (634, 0.022875450543583874),
 (635, 0.033389028164708894),
 (636, 0.0),
 (637, 0.0595843591724218),
 (638, 0.0),
 (639, 0.0),
 (640, 0.10256410256410256),
 (641, 0.04941662111074008),
 (642, 0.04358136336404089),
 (643, 0.05264981264926564),
 (644, 0.04828045495852676),
 (645, 0.03026137663344012),
 (646, 0.0),
 (647, 0.05128205128205128),
 (648, 0.0),
 (649, 0.04241898419838518),
 (650, 0.10741723110591492),
 (651, 0.12201777521731264),
 (652, 0.02360960823249428),
 (653, 0.0),
 (654, 0.05120915564991892),
 (655, 0.07242068243779014),
 (656, 0.025318484177091666),
 (657, 0.09245003270420485),
 (658, 0.18452078282356416),
 (659, 0.0),
 (660, 0.0),
 (661, 0.05847053462046861),
 (662, 0.06726727939963124),
 (663, 0.04941662111074008),
 (664, 0.0),
 (665, 0.1307440900921227),
 (666, 0.03580574370197164),
 (667, 0.01736833685729687),
 (668, 0.06661733875264912),
 (669, 0.027874733666903028),
 (670, 0.03942082639927217),
 (671, 0.09245003270420486),
 (672, 0.06661733875264912),
 (673, 0.027874733666903028),
 (674, 0.025007816164017767),
 (675, 0.11503946170861017),
 (676, 0.0),
 (677, 0.07412493166611012),
 (678, 0.027461751819054483),
 (679, 0.019710413199636085),
 (680, 0.04774099160262886),
 (681, 0.0),
 (682, 0.03202563076101743),
 (683, 0.030816677568068284),
 (684, 0.10390486669322622),
 (685, 0.042796049251091296),
 (686, 0.0),
 (687, 0.02470831055537004),
 (688, 0.05847053462046861),
 (689, 0.10795837927188262),
 (690, 0.03413943709994594),
 (691, 0.021790681682020446),
 (692, 0.06677805632941779),
 (693, 0.021398024625545648),
 (694, 0.0),
 (695, 0.042796049251091296),
 (696, 0.03774256780481986),
 (697, 0.027874733666903028),
 (698, 0.05661385170722978),
 (699, 0.022422426466543747),
 (700, 0.02120949209919259),
 (701, 0.06726727939963124),
 (702, 0.02414022747926338),
 (703, 0.021591675854376526),
 (704, 0.0),
 (705, 0.02470831055537004),
 (706, 0.020336295869552105),
 (707, 0.05741692517632145),
 (708, 0.05195243334661311),
 (709, 0.0),
 (710, 0.025007816164017767),
 (711, 0.0),
 (712, 0.09805806756909202),
 (713, 0.026688025634181187),
 (714, 0.0),
 (715, 0.06661733875264912),
 (716, 0.0),
 (717, 0.05128205128205128),
 (718, 0.03202563076101743),
 (719, 0.0),
 (720, 0.04774099160262886),
 (721, 0.02360960823249428),
 (722, 0.0),
 (723, 0.0),
 (724, 0.03039738350583688),
 (725, 0.09443843292997713),
 (726, 0.04828045495852676),
 (727, 0.029864054671577652),
 (728, 0.05195243334661311),
 (729, 0.08968970586617499),
 (730, 0.060522753266880225),
 (731, 0.06598588053218755),
 (732, 0.08716272672808179),
 (733, 0.029235267310234306),
 (734, 0.07692307692307693),
 (735, 0.0),
 (736, 0.03774256780481986),
 (737, 0.12725695259515554),
 (738, 0.055749467333806056),
 (739, 0.02973505167250263),

In [88]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0000000000000002),
 (1211, 0.29783231641997604),
 (506, 0.2710098294963041),
 (538, 0.2706659809803833),
 (2402, 0.26257545381445874),
 (1189, 0.2614881801842454),
 (581, 0.26148818018424536),
 (1199, 0.2597056905574371),
 (3725, 0.25715142542972574),
 (61, 0.2562050460881395),
 (775, 0.2491009475118111),
 (1913, 0.24419314525275215),
 (2779, 0.24209101306752093),
 (4043, 0.24037008503093257),
 (4401, 0.24019223070763068),
 (969, 0.2338821384818744),
 (321, 0.23076923076923073),
 (970, 0.2300789234172203),
 (2326, 0.22422426466543746),
 (4187, 0.22417941532712204),
 (576, 0.2229978693352242),
 (74, 0.22205779584216379),
 (3603, 0.2201762114819948),
 (3668, 0.21726204731337043),
 (1084, 0.21618989813247),
 (494, 0.21571674297647797),
 (1196, 0.21571674297647797),
 (2994, 0.21483446221182986),
 (3322, 0.21483446221182984),
 (47, 0.21204880838762138),
 (94, 0.21182963643408081),
 (1316, 0.20965696734438366),
 (2966, 0.2090408714859538),
 (1270, 0.20814536170751838),
 (1324, 0.20814536170751838),
 (4, 0.2080125735844609),
 (304, 0.20672455764868075),
 (172, 0.20483662259967567),
 (151, 0.20483662259967564),
 (372, 0.20483662259967564),
 (259, 0.20464687117164013),
 (219, 0.2046468711716401),
 (1350, 0.20380986614602725),
 (3994, 0.20131905799006777),
 (1437, 0.20016019225635892),
 (1066, 0.2000625293121421),
 (2197, 0.1976664844429603),
 (4332, 0.1976664844429603),
 (27, 0.1971041319963609),
 (83, 0.19611613513818402),
 (168, 0.1953545162022017),
 (184, 0.1953545162022017),
 (928, 0.19512313566832118),
 (36, 0.19312181983410703),
 (91, 0.19223226273338134),
 (1975, 0.19223226273338134),
 (1767, 0.1921537845661046),
 (299, 0.19096396641051544),
 (939, 0.18887686585995425),
 (1824, 0.18887686585995425),
 (3533, 0.18887686585995425),
 (41, 0.18685673434682065),
 (108, 0.18490006540840973),
 (31, 0.1849000654084097),
 (2508, 0.1849000654084097),
 (150, 0.18490006540840964),
 (3157, 0.18452078282356418),
 (658, 0.18452078282356416),
 (67, 0.18427434427242975),
 (580, 0.1815682598006407),
 (2724, 0.1815682598006407),
 (594, 0.18116432546313532),
 (1530, 0.18116432546313532),
 (486, 0.17841031003501578),
 (341, 0.17792017089454126),
 (26, 0.17505471314812437),
 (1376, 0.17295817388759027),
 (2068, 0.17255919256291524),
 (149, 0.17225077552896437),
 (4344, 0.17118419700436519),
 (310, 0.17093520167692652),
 (111, 0.1709352016769265),
 (1339, 0.1709352016769265),
 (465, 0.1706971854997297),
 (489, 0.1706971854997297),
 (1481, 0.1706971854997297),
 (835, 0.16984155512168939),
 (274, 0.16984155512168933),
 (52, 0.16898159235484367),
 (412, 0.16724840200141816),
 (3349, 0.16724840200141816),
 (7, 0.167093470609201),
 (528, 0.167093470609201),
 (56, 0.16694514082354447),
 (248, 0.16694514082354447),
 (1292, 0.16526725762745997),
 (46, 0.16477051091432687),
 (2753, 0.16401847362094593),
 (1931, 0.16349964255346808),
 (504, 0.1634301126151534),
 (460, 0.16239958858823),
 (856, 0.16239958858823),
 (2162, 0.16239958858823),
 (3404, 0.16239958858823),
 (127, 0.1621424235993525),
 (1268, 0.16178755723235852),
 (95, 0.1617875572323585),
 (1051, 0.1617875572323585),
 (1472, 0.1613940087116806),
 (475, 0.16012815380508716),
 (1366, 0.16012815380508716),
 (2371, 0.16012815380508716),
 (72, 0.16012815380508713),
 (1389, 0.16012815380508713),
 (4074, 0.16012815380508713),
 (1958, 0.15889162445979146),
 (1801, 0.15794943794779692),
 (1173, 0.15585730003983933),
 (1553, 0.15585730003983933),
 (4005, 0.15534712747612348),
 (482, 0.15408338784034142),
 (1153, 0.15408338784034142),
 (472, 0.1539670545751043),
 (158, 0.15253477177414312),
 (501, 0.15253477177414312),
 (14, 0.15191090506255),
 (187, 0.15191090506255),
 (1091, 0.1513068831672006),
 (2965, 0.1513068831672006),
 (1317, 0.15097027121927944),
 (1708, 0.15097027121927944),
 (1081, 0.1500468969841066),
 (4224, 0.1500468969841066),
 (2126, 0.14978617237881955),
 (68, 0.14867525836251314),
 (512, 0.14824986333222023),
 (2866, 0.147180996735913),
 (1568, 0.146943671674129),
 (166, 0.1465158871516513),
 (751, 0.1465158871516513),
 (2443, 0.1465158871516513),
 (3623, 0.1465158871516513),
 (999, 0.14617633655117152),
 (1269, 0.14617633655117152),
 (1651, 0.14617633655117152),
 (3371, 0.14617633655117152),
 (4669, 0.14617633655117152),
 (3629, 0.14484136487558028),
 (578, 0.1437993271357627),
 (1042, 0.1437993271357627),
 (1826, 0.1437993271357627),
 (255, 0.14322297480788657),
 (1294, 0.14322297480788657),
 (2316, 0.14322297480788657),
 (102, 0.14235407108686474),
 (1734, 0.14235407108686474),
 (364, 0.1416576493949657),
 (548, 0.1416576493949657),
 (567, 0.14153462926807447),
 (28, 0.14153462926807445),
 (122, 0.14153462926807445),
 (293, 0.14153462926807445),
 (421, 0.14153462926807445),
 (1871, 0.14121975762272054),
 (867, 0.1401425507601155),
 (897, 0.1401425507601155),
 (3230, 0.1401425507601155),
 (200, 0.13977131156292244),
 (1494, 0.13977131156292244),
 (1517, 0.13977131156292244),
 (2489, 0.13937366833451514),
 (277, 0.1386750490563073),
 (17, 0.13797289239745258),
 (231, 0.1373087590952724),
 (182, 0.13725270326150324),
 (1610, 0.13725270326150324),
 (2540, 0.13725270326150324),
 (997, 0.13693937303317935),
 (1322, 0.13655774839978377),
 (2154, 0.13655774839978377),
 (3776, 0.13655774839978377),
 (453, 0.1358732440973515),
 (87, 0.13533299049019168),
 (1215, 0.1345345587992625),
 (4534, 0.1345345587992625),
 (232, 0.13355611265883557),
 (932, 0.13355611265883557),
 (3977, 0.13355611265883557),
 (448, 0.13344012817090595),
 (840, 0.13344012817090595),
 (1026, 0.13344012817090595),
 (2065, 0.13344012817090595),
 (1411, 0.13323467750529824),
 (1490, 0.1320989873168695),
 (43, 0.1319717610643751),
 (419, 0.1319717610643751),
 (774, 0.1319717610643751),
 (3493, 0.1316245316231641),
 (318, 0.1307440900921227),
 (665, 0.1307440900921227),
 (1877, 0.1307440900921227),
 (2046, 0.1307440900921227),
 (2577, 0.1307440900921227),
 (3656, 0.1307440900921227),
 (3949, 0.1307440900921227),
 (123, 0.13074409009212268),
 (1505, 0.13074409009212268),
 (1010, 0.12988108336653278),
 (227, 0.12955005512625914),
 (3304, 0.12955005512625914),
 (269, 0.1283881477532739),
 (2473, 0.1283881477532739),
 (2789, 0.1283881477532739),
 (2849, 0.1283881477532739),
 (3625, 0.1283881477532739),
 (138, 0.1282051282051282),
 (811, 0.1282051282051282),
 (2174, 0.1282051282051282),
 (3617, 0.1282051282051282),
 (85, 0.12810252304406974),
 (33, 0.12810252304406972),
 (35, 0.12810252304406972),
 (134, 0.12810252304406972),
 (367, 0.12810252304406972),
 (1275, 0.12810252304406972),
 (4013, 0.12810252304406972),
 (4193, 0.12810252304406972),
 (4327, 0.12810252304406972),
 (4486, 0.12810252304406972),
 (737, 0.12725695259515554),
 (3088, 0.12725695259515554),
 (206, 0.12691660175143157),
 (10, 0.12659242088545833),
 (222, 0.12659242088545833),
 (1032, 0.12659242088545833),
 (1190, 0.12659242088545833),
 (2679, 0.12659242088545833),
 (3750, 0.12659242088545833),
 (4668, 0.126155140059354),
 (237, 0.1261107739106075),
 (1567, 0.1261107739106075),
 (3207, 0.12580855934939952),
 (361, 0.12561485860426555),
 (770, 0.12561485860426555),
 (1151, 0.12561485860426555),
 (1935, 0.12561485860426555),
 (4250, 0.12561485860426555),
 (4399, 0.12561485860426555),
 (540, 0.125081459767525),
 (368, 0.12503908082008885),
 (126, 0.12503908082008883),
 (507, 0.12503908082008883),
 (1489, 0.12403473458920845),
 (1996, 0.12403473458920844),
 (934, 0.1235415527768502),
 (1077, 0.1235415527768502),
 (208, 0.12326671027227314),
 (2053, 0.12326671027227314),
 (228, 0.12303443814151493),
 (936, 0.12229989761755714),
 (556, 0.12209657262637608),
 (1607, 0.12209657262637608),
 (651, 0.12201777521731264),
 (84, 0.12201777521731262),
 (2432, 0.12201777521731262),
 (2491, 0.12201777521731262),
 (510, 0.12104550653376048),
 (917, 0.12104550653376048),
 (1467, 0.12104550653376048),
 (2086, 0.12104550653376048),
 (2638, 0.12104550653376048),
 (265, 0.1207011373963169),
 (437, 0.1207011373963169),
 (509, 0.1207011373963169),
 (1394, 0.1207011373963169),
 (3930, 0.1207011373963169),
 (2324, 0.12009611535381534),
 (2667, 0.12009611535381534),
 (2782, 0.12009611535381534),
 (3078, 0.12009611535381534),
 (3213, 0.12009611535381534),
 (3900, 0.12009611535381534),
 (4733, 0.12009611535381534),
 (479, 0.11935247900657214),
 (2277, 0.11935247900657214),
 (139, 0.11916871834484359),
 (778, 0.11894020669001051),
 (975, 0.11894020669001051),
 (1301, 0.11894020669001051),
 (1749, 0.11894020669001051),
 (2645, 0.11894020669001051),
 (3731, 0.11894020669001051),
 (1398, 0.1182624791978165),
 (333, 0.1180480411624714),
 (370, 0.1180480411624714),
 (409, 0.1180480411624714),
 (2234, 0.1180480411624714),
 (362, 0.11737660545701087),
 (399, 0.11694106924093722),
 (563, 0.11694106924093722),
 (1296, 0.11694106924093722),
 (411, 0.11678545896676293),
 (1666, 0.11651034560709261),
 (3995, 0.11651034560709261),
 (4650, 0.11651034560709261),
 (3716, 0.1165103456070926),
 (160, 0.11561170597113389),
 (235, 0.11503946170861017),
 (675, 0.11503946170861017),
 (1582, 0.11503946170861017),
 (2653, 0.11503946170861017),
 (2734, 0.11503946170861017),
 (588, 0.11483385035264292),
 (810, 0.11437725271791938),
 (2481, 0.11437725271791938),
 (2813, 0.11437725271791938),
 (189, 0.11322770341445959),
 (4469, 0.11322770341445959),
 (50, 0.11322770341445956),
 (4541, 0.11244949691847501),
 (18, 0.11168711865749101),
 (121, 0.11149893466761211),
 (772, 0.11149893466761211),
 (957, 0.11149893466761211),
 (1609, 0.11149893466761211),
 (2576, 0.11149893466761211),
 (535, 0.11102889792108189),
 (992, 0.11102889792108188),
 (1228, 0.11102889792108188),
 (431, 0.11102889792108186),
 (886, 0.11098534863604863),
 (3142, 0.11094003924504581),
 (300, 0.11020775375559676),
 (805, 0.11020775375559674),
 (847, 0.11020775375559674),
 (1000, 0.11020775375559674),
 (1343, 0.11020775375559674),
 (2107, 0.11020775375559674),
 (4160, 0.11020775375559674),
 (2365, 0.10997646755364592),
 (21, 0.10984700727621793),
 (203, 0.10984700727621793),
 (3003, 0.10984700727621793),
 (4464, 0.10984700727621793),
 (796, 0.10948978029027179),
 (81, 0.10878565864408421),
 (3423, 0.10826639239215335),
 (1938, 0.10826639239215334),
 (229, 0.108094949066235),
 (5, 0.10795837927188262),
 (169, 0.10795837927188262),
 (616, 0.10795837927188262),
 (689, 0.10795837927188262),
 (3548, 0.10795837927188262),
 (238, 0.10741723110591492),
 (625, 0.10741723110591492),
 (650, 0.10741723110591492),
 (2319, 0.10741723110591492),
 (2374, 0.10741723110591492),
 (3426, 0.10741723110591492),
 (306, 0.10736246830291345),
 (571, 0.10699012312772824),
 (749, 0.10699012312772824),
 (1825, 0.10699012312772824),
 (39, 0.10675210253672475),
 (331, 0.10675210253672475),
 (471, 0.10675210253672475),
 (783, 0.10675210253672475),
 (4773, 0.10675210253672475),
 (261, 0.10604746049596296),
 (1014, 0.10604746049596296),
 (3551, 0.10604746049596296),
 (1013, 0.10604746049596295),
 (305, 0.10529962529853128),
 (624, 0.10529962529853128),
 (1232, 0.10529962529853128),
 (2637, 0.10529962529853128),
 (3921, 0.10529962529853128),
 (4622, 0.10529962529853128),
 (170, 0.105129283382795),
 (1161, 0.10482848367219183),
 (1738, 0.10482848367219183),
 (2514, 0.10482848367219183),
 (2627, 0.10482848367219183),
 (4130, 0.10482848367219183),
 (4427, 0.10482848367219183),
 (466, 0.10423454980627081),
 (131, 0.10390486669322622),
 (241, 0.10390486669322622),
 (294, 0.10390486669322622),
 (684, 0.10390486669322622),
 (851, 0.10390486669322622),
 (1284, 0.10390486669322622),
 (1764, 0.10390486669322622),
 (3335, 0.10390486669322622),
 (402, 0.10336227882434038),
 (1632, 0.10336227882434038),
 (16, 0.10256410256410256),
 (75, 0.10256410256410256),
 (640, 0.10256410256410256),
 (2141, 0.10256410256410256),
 (2810, 0.10256410256410256),
 (3097, 0.10256410256410256),
 (2099, 0.1025115460130912),
 (105, 0.10241831129983783),
 (2449, 0.10241831129983783),
 (2755, 0.10241831129983783),
 (3616, 0.10241831129983783),
 (3834, 0.10241831129983783),
 (157, 0.10241831129983782),
 (2441, 0.10241831129983782),
 (3050, 0.10241831129983782),
 (1448, 0.10168147934776052),
 (96, 0.10127393670836667),
 (174, 0.10127393670836667),
 (919, 0.10127393670836667),
 (1108, 0.10127393670836667),
 (2933, 0.10127393670836667),
 (3023, 0.10127393670836667),
 (3147, 0.10127393670836667),
 (3869, 0.10127393670836667),
 (4092, 0.10127393670836667),
 (45, 0.10087125544480038),
 (622, 0.10016708449412667),
 (1072, 0.10016708449412667),
 (3886, 0.10016708449412667),
 (3989, 0.10016708449412667),
 (3436, 0.10008009612817945),
 (70, 0.10003126465607107),
 (101, 0.10003126465607107),
 (207, 0.10003126465607107),
 (311, 0.10003126465607107),
 (329, 0.10003126465607107),
 (630, 0.10003126465607107),
 (1289, 0.10003126465607107),
 (2014, 0.10003126465607107),
 (2240, 0.10003126465607107),
 (4687, 0.10003126465607107),
 (103, 0.09930726528736966),
 (490, 0.09930726528736966),
 (1432, 0.09930726528736966),
 (2092, 0.09930726528736966),
 (82, 0.09883324222148016),
 (444, 0.09883324222148016),
 (983, 0.09883324222148016),
 (1516, 0.09883324222148016),
 (1785, 0.09883324222148016),
 (2911, 0.09883324222148016),
 (4554, 0.09883324222148016),
 (2379, 0.09805806756909204),
 (262, 0.09805806756909202),
 (712, 0.09805806756909202),
 (875, 0.09805806756909202),
 (2780, 0.09805806756909202),
 (51, 0.09781383788084239),
 (221, 0.09781383788084239),
 (1768, 0.09781383788084239),
 (2156, 0.09767725810110087),
 (3615, 0.09767725810110087),
 (3778, 0.09767725810110087),
 (4040, 0.09767725810110087),
 (1821, 0.09709195467257717),
 (9, 0.09656090991705352),
 (534, 0.09656090991705352),
 (632, 0.09656090991705352),
 (895, 0.09656090991705352),
 (1104, 0.09656090991705352),
 (1816, 0.09656090991705352),
 (2246, 0.09656090991705352),
 (2388, 0.09656090991705352),
 (324, 0.09607689228305229),
 (1714, 0.09607689228305229),
 (1720, 0.09607689228305229),
 (2252, 0.09607689228305229),
 (2555, 0.09607689228305229),
 (4468, 0.09607689228305229),
 (905, 0.09548198320525772),
 (1616, 0.09548198320525772),
 (3017, 0.09548198320525772),
 (3555, 0.09501857794816083),
 (11, 0.09443843292997713),
 (725, 0.09443843292997713),
 (974, 0.09443843292997713),
 (1163, 0.09443843292997713),
 (1989, 0.09443843292997713),
 (2549, 0.09443843292997713),
 (148, 0.09421114395319916),
 (788, 0.09421114395319916),
 (1257, 0.09421114395319916),
 (2261, 0.09421114395319916),
 (2263, 0.09421114395319916),
 (3567, 0.09421114395319916),
 (3896, 0.09421114395319916),
 (4198, 0.09421114395319916),
 (76, 0.09342836717341034),
 (270, 0.09342836717341034),
 (586, 0.09342836717341034),
 (2824, 0.09342836717341034),
 (3459, 0.09342836717341034),
 (4078, 0.09342836717341034),
 (193, 0.09331812717375042),
 (93, 0.09245003270420486),
 (242, 0.09245003270420486),
 (671, 0.09245003270420486),
 (1271, 0.09245003270420486),
 (1352, 0.09245003270420486),
 (1625, 0.09245003270420486),
 (1685, 0.09245003270420486),
 (2585, 0.09245003270420486),
 (2643, 0.09245003270420486),
 (2694, 0.09245003270420486),
 (3715, 0.09245003270420486),
 (4498, 0.09245003270420486),
 (657, 0.09245003270420485),
 (1022, 0.09245003270420485),
 (1566, 0.09245003270420485),
 (1679, 0.09245003270420485),
 (2389, 0.09245003270420485),
 (3532, 0.09245003270420485),
 (4267, 0.09245003270420485),
 (595, 0.0915018021743355),
 (1439, 0.0915018021743355),
 (1694, 0.0915018021743355),
 (782, 0.09124148357522649),
 (12, 0.09078412990032037),
 (218, 0.09078412990032037),
 (243, 0.09078412990032037),
 (355, 0.09078412990032037),
 (2083, 0.09078412990032037),
 (2644, 0.09078412990032037),
 (1983, 0.09065471553673685),
 (97, 0.09058216273156766),
 (278, 0.09058216273156766),
 (418, 0.09058216273156766),
 (779, 0.09058216273156766),
 (1273, 0.09058216273156766),
 (3295, 0.09058216273156766),
 (3402, 0.09058216273156766),
 (2563, 0.09007912422186248),
 (600, 0.08968970586617499),
 (729, 0.08968970586617499),
 (1839, 0.08968970586617499),
 (3876, 0.08968970586617499),
 (88, 0.08920515501750789),
 (167, 0.08920515501750789),
 (388, 0.08920515501750789),
 (1473, 0.08920515501750789),
 (1937, 0.08920515501750789),
 (2244, 0.08920515501750789),
 (2952, 0.08920515501750789),
 (4562, 0.08920515501750789),
 (59, 0.08896008544727063),
 (2356, 0.0888231183368655),
 (2843, 0.0888231183368655),
 (3384, 0.0888231183368655),
 (3438, 0.0888231183368655),
 (3457, 0.0888231183368655),
 (4118, 0.0888231183368655),
 (4349, 0.0888231183368655),
 (273, 0.08861469461982083),
 (330, 0.08798117404291673),
 (1899, 0.08798117404291673),
 (3385, 0.08798117404291673),
 (3905, 0.08798117404291673),
 (2108, 0.08788174152965353),
 (23, 0.08770580193070292),
 (291, 0.08770580193070292),
 (357, 0.08770580193070292),
 (456, 0.08770580193070292),
 (1342, 0.08770580193070292),
 (1427, 0.08770580193070292),
 (2861, 0.08770580193070292),
 (3317, 0.08770580193070292),
 (3444, 0.08770580193070292),
 (4266, 0.08770580193070292),
 (4676, 0.08770580193070292),
 (125, 0.08752735657406217),
 (212, 0.08716272672808179),
 (732, 0.08716272672808179),
 (1776, 0.08716272672808179),
 (2102, 0.08716272672808179),
 (2706, 0.08716272672808179),
 (4339, 0.08716272672808179),
 (478, 0.08684168428648435),
 (199, 0.0863667034175061),
 (2733, 0.0863667034175061),
 (183, 0.08633531446374632),
 (2756, 0.08633531446374632),
 (2, 0.08627959628145762),
 (141, 0.08627959628145762),
 (742, 0.08627959628145762),
 (791, 0.08627959628145762),
 (1068, 0.08627959628145762),
 (1244, 0.08627959628145762),
 (1254, 0.08627959628145762),
 (1624, 0.08627959628145762),
 (3443, 0.08627959628145762),
 (3510, 0.08627959628145762),
 (143, 0.08559209850218259),
 (533, 0.08559209850218259),
 (824, 0.08559209850218259),
 (1523, 0.08559209850218259),
 (2128, 0.08559209850218259),
 (2589, 0.08559209850218259),
 (2873, 0.08559209850218259),
 (4512, 0.08559209850218259),
 (4583, 0.08559209850218259),
 (1092, 0.08492077756084468),
 (1371, 0.08492077756084468),
 (3130, 0.08492077756084468),
 (3360, 0.08492077756084468),
 (4750, 0.08492077756084468),
 (4786, 0.08492077756084468),
 (32, 0.08483796839677037),
 (129, 0.08483796839677037),
 (233, 0.08483796839677037),
 (2045, 0.08483796839677037),
 (2963, 0.08483796839677037),
 (48, 0.084103426706236),
 (217, 0.084103426706236),
 (1006, 0.084103426706236),
 (1300, 0.084103426706236),
 (1, 0.08362420100070908),
 (142, 0.08362420100070908),
 (440, 0.08362420100070908),
 (546, 0.08362420100070908),
 (891, 0.08362420100070908),
 (1137, 0.08362420100070908),
 (2297, 0.08362420100070908),
 (4253, 0.08362420100070908),
 (4556, 0.08362420100070908),
 (190, 0.08338763984501665),
 (2257, 0.08338763984501665),
 (2883, 0.08338763984501665),
 (19, 0.0826898230594723),
 (62, 0.0826898230594723),
 (380, 0.0826898230594723),
 (1657, 0.0826898230594723),
 (1691, 0.0826898230594723),
 (2332, 0.0826898230594723),
 (2347, 0.0826898230594723),
 (3001, 0.0826898230594723),
 (3149, 0.0826898230594723),
 (3175, 0.0826898230594723),
 (3973, 0.0826898230594723),
 (4070, 0.0826898230594723),
 (4564, 0.0826898230594723),
 (152, 0.08238525545716345),
 (226, 0.08238525545716345),
 (314, 0.08238525545716345),
 (340, 0.08238525545716345),
 (365, 0.08238525545716345),
 (1236, 0.08238525545716345),
 (1681, 0.08238525545716345),
 (2121, 0.08238525545716345),
 (79, 0.08200923681047297),
 (2196, 0.08134518347820842),
 (1202, 0.081199794294115),
 (1742, 0.081199794294115),
 (1761, 0.081199794294115),
 (2160, 0.081199794294115),
 (2629, 0.081199794294115),
 (2654, 0.081199794294115),
 (3132, 0.081199794294115),
 (3135, 0.081199794294115),
 (3296, 0.081199794294115),
 (3465, 0.081199794294115),
 (63, 0.0806970043558403),
 (374, 0.0806970043558403),
 (500, 0.0806970043558403),
 (38, 0.08006407690254357),
 (244, 0.08006407690254357),
 (583, 0.08006407690254357),
 (784, 0.08006407690254357),
 (809, 0.08006407690254357),
 (863, 0.08006407690254357),
 (898, 0.08006407690254357),
 (1027, 0.08006407690254357),
 (1264, 0.08006407690254357),
 (1512, 0.08006407690254357),
 (2664, 0.08006407690254357),
 (2858, 0.08006407690254357),
 (2870, 0.08006407690254357),
 (3522, 0.08006407690254357),
 (4488, 0.08006407690254357),

In [89]:
#top 5 movies
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1211, 0.29783231641997604),
 (506, 0.2710098294963041),
 (538, 0.2706659809803833),
 (2402, 0.26257545381445874),
 (1189, 0.2614881801842454)]

In [93]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(i[0])

In [94]:
recommend('Avatar')

1211
506
538
2402
1189

In [95]:
new_df.iloc[1211].title

'Aliens vs Predator: Requiem'

In [ ]:
#instead of vectors we need similar movies names so

In [96]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [97]:
recommend('Avatar')

Aliens vs Predator: Requiem
Independence Day
Titan A.E.
Aliens
Small Soldiers